# Generated by Django 4.1.7 on 2023-03-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
    ]
