# Generated by Django 4.1.7 on 2023-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_cadastro_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
