# Generated by Django 4.1.7 on 2023-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_alter_cadastro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
