# Generated by Django 4.1.7 on 2023-03-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0005_alter_cadastro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='id',
            new_name='cadastro_id',
        ),
    ]
