# Generated by Django 4.1.7 on 2023-03-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_rename_id_cadastro_cadastro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='cadastro_id',
            new_name='id',
        ),
    ]
