# Generated by Django 4.2 on 2023-05-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
