import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from '@/contexts';
import { Login } from '@/components/login';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
        <Login>
          <div className='p-16'>
            {children}
          </div>
        </Login>
        </AuthProvider>
      </body>
    </html>
  )
}
