export const tipos = [
	'CICLOMOTOR',
	'MOTONETA',
	'MOTOCICLETA',
	'TRICICLO',
	'AUTOMOVEL',
	'MICROONIBUS',
	'ONIBUS',
	'REBOQUE',
	'SEMI_REBOQUE',
	'CAMIONETA',
	'CAMINHAO',
	'CAMINHAO_TRATOR',
	'TRATOR_DE_RODAS',
	'TRATOR_DE_ESTEIRAS',
	'TRATOR_MISTO',
	'QUADRICICLO',
	'CHASSI_PLATAFORMA',
	'CAMINHONETE',
	'SIDE_CAR',
	'UTILITARIO',
	'MOTOR_CASA'
  ]
  
  export const categorias = [
	'PARTICULAR',
	'ALUGUEL',
	'OFICIAL',
	'EXPERIENCIA',
	'APRENDIZAGEM',
	'FABRICANTE',
	'CORPO_CONSULAR',
	'ORGANISMOS_INTERNACIONAIS',
	'CHEFE_DE_MISSAO_DIPLOMATICA',
	'CORPO_DIPLOMATICO',
	'MISSAO_REPARTICAO_REPRESENTACAO',
	'AC_DE_COOPERACAO_INTERNACIONAL'
  ]
  
  export const tiposPlacas = [
	'dianteira',
	'segundaTraseira',
	'traseira',
  ]
  
  
  export const especies = [
	'PASSAGEIROS',
	'CARGA',
	'MISTO',
	'COMPETICAO',
	'TRACAO',
	'ESPECIAL',
	'COLECAO'
  ]
  